### ISSUE TITLE
Testing on GitHub

### ISSUE THREAD

**Issue by gmunkhbaatarmn** [atulga/MNsticker#1]
Woohoo!

![](http://gallery.raccoonfink.com/d/7003-2/alien-head-128x128.png)

**Comment by ariunbayar** [comment]
![](http://gallery.raccoonfink.com/d/7003-2/alien-head-128x128.png)

**Comment by ariunbayar** [comment]
![](http://gallery.raccoonfink.com/d/7003-2/alien-head-128x128.png)

![](http://gallery.raccoonfink.com/d/7003-2/alien-head-128x128.png)

**Comment by gmunkhbaatarmn** [comment]
Үүнийг хийх амархан уу?

![](https://raw.githubusercontent.com/atulga/MNsticker/images/static/1235097_419934721439480_1167444181_n.jpg)

**Comment by Zorig** [comment]
![](https://raw.githubusercontent.com/atulga/MNsticker/images/static/1236550_419934648106154_827335100_n.jpg)

**Comment by Zorig** [comment]
![](https://raw.githubusercontent.com/atulga/MNsticker/images/static/10696198_619217908199870_7188995612379070326_n.jpg)

![](https://raw.githubusercontent.com/atulga/MNsticker/images/static/11025658_807733875968521_1065455227816261074_n.jpg)

**Comment by gmunkhbaatarmn** [comment]
Published: https://chrome.google.com/webstore/detail/aendbinkaphfchakmkldhioejeaahkgb
